<style type="text/css">
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-slider-title {
		text-align:<?php echo $slidertitleposition;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-slider-title h2 {
		color:<?php echo $slidertitlecolor;?>;
		font-size:<?php echo $slidertitlefontsize."px";?>;
		font-weight: <?php echo $slidertitlefweight;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-title {
		text-align:<?php echo $ocpc_posttitleposition;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-title a {
		color:<?php echo $ocpc_posttitlecolor;?>;
		font-size:<?php echo $ocpc_posttitlefontsize."px";?>;
		font-weight: <?php echo $ocpc_posttitlefweight;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-moretext a {
    	color: <?php echo $readmoretextcolor;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-date {
		text-align:<?php echo $ocpc_postdateposition;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-date span {
		color:<?php echo $ocpc_postdatecolor;?>;
		font-size:<?php echo $ocpc_postdatefontsize."px";?>;
		font-weight:<?php echo $ocpc_postdatefweight;?>;
	}
	.ocpc-categories {
	    text-align:<?php echo $ocpc_postcatsposition;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-categories span {
        color:<?php echo $ocpc_postcatscolor;?>;
        font-size:<?php echo $ocpc_postcatsfontsize."px";?>;
        font-weight:<?php echo $ocpc_postcatsfweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc-categories span a {
        color:<?php echo $ocpc_postcatscolor;?>;
        font-size:<?php echo $ocpc_postcatsfontsize."px";?>;
        font-weight:<?php echo $ocpc_postcatsfweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc-categories svg {
        width: <?php echo $ocpc_postcatsfontsize."px";?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc-categories svg path {
        fill: <?php echo $ocpc_postcatscolor;?>;
    }
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-author {
		text-align:<?php echo $ocpc_postauthorposition;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-author span {
		color:<?php echo $ocpc_postauthorcolor;?>;
		font-size:<?php echo $ocpc_postauthorfontsize."px";?>;
		font-weight:<?php echo $ocpc_postauthorfweight;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpc-content {
		color:<?php echo $ocpc_postdescriptioncolor;?>;
		font-size:<?php echo $ocpc_postdescriptionfontsize."px";?>;
		text-align:<?php echo $ocpc_postdescriptionposition;?>;
		font-weight:<?php echo $ocpc_postdescriptionfweight;?>;
	}
	.ocpc_slider_id_<?php echo $id; ?>.oc_post_layout.ocpc-template-1.carousel .ocpc-main<?php echo $ocpc_random_number_id; ?>.owl-theme .owl-nav {
	  	top:25% !important;
	}
	.ocpc_slider_id_<?php echo $id; ?>.oc_post_layout.ocpc-template-5.carousel .ocpc-main<?php echo $ocpc_random_number_id; ?>.owl-theme .owl-nav {
	    top: 28% !important;
	}
	.ocpc-main<?php echo $ocpc_random_number_id; ?>.owl-theme .owl-nav {
	  	position: absolute !important;
	  	top: 40% !important;
	  	width: 100% !important;
	  	margin: 0 !important;
	  	padding: 0 !important;
	}
	.ocpc-main<?php echo $ocpc_random_number_id; ?>.owl-theme .owl-nav [class*=owl-] {
	    font-size: 0px;
	    border-radius: 0;
	    padding: 0;
	    width: 30px;
    	height: 50px;
	    text-align: center;
	    line-height: 0;
	}
	.ocpc-main<?php echo $ocpc_random_number_id; ?> .owl-prev {
	    left: 0px;
	    position: absolute;
	}
	.ocpc-main<?php echo $ocpc_random_number_id; ?> .owl-next {
	    right: 0px;
	    position: absolute;
	}
	.ocpc-main<?php echo $ocpc_random_number_id; ?> div.owl-prev:after {
	    content: "\f053";
	    font-family: 'FontAwesome';
	    color: #000;
	    font-size: 18px;
	    left: -1px;
	    position: relative;
	}
	.ocpc-main<?php echo $ocpc_random_number_id; ?> div.owl-next:after {
	    content: "\f054";
	    font-family: 'FontAwesome';
	    color: #000;
	    font-size: 18px;
	    right: -1px;
	    position: relative;
	}
	.ocpc_slider_id_<?php echo $id; ?>.ocpc_post_layout.ocpc-template-1 .ocpc_discripton_class {
		background: <?php echo $ocpc_trbgcolor; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?>.ocpc_post_layout.ocpc-template-2 .ocpc_discripton_class {
		background: <?php echo $ocpc_trbgcolor; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?>.ocpc_post_layout.ocpc-template-4 .ocpc_discripton_class {
		background: <?php echo $ocpc_trbgcolor; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?>.ocpc_post_layout.ocpc-template-5 .ocpc_discripton_class {
    	background: <?php echo $ocpc_trbgcolor; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpost_page.pagination a.page-numbers {
		background-color: <?php echo $ocpc_pagibgclr; ?>;
    	color: <?php echo $ocpc_pagitxtclr; ?>;
		border-radius: <?php echo $pagi_num_radious; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpost_page.pagination a.page-numbers.prev, .ocpc_slider_id_<?php echo $id; ?> .ocpost_page.pagination a.page-numbers.next {
		border-radius: <?php echo $pagi_nextprev_radious; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpost_page.pagination .page-numbers.dots {
    	color: <?php echo $ocpc_pagibgclr; ?>;
	}
	.ocpc_slider_id_<?php echo $id; ?> .ocpost_page.pagination .current {
		border-radius: <?php echo $pagi_num_radious; ?>;
	}


	/*new templates after template no.5 css starts*/
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_main,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_main
	{
        background: <?php echo $ocpc_trbgcolor; ?> none repeat scroll 0 0;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_title,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_title,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_title
    {
        text-align:<?php echo $ocpc_posttitleposition;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_title a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_title a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_title a
    {
        color:<?php echo $ocpc_posttitlecolor;?>;
        font-size:<?php echo $ocpc_posttitlefontsize."px";?>;
        font-weight: <?php echo $ocpc_posttitlefweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_dec .ocpc-moretext a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_dec .ocpc-moretext a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_dec .ocpc-moretext a
    {
        color: <?php echo $readmoretextcolor;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_date,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_date,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_date
    {
        text-align:<?php echo $ocpc_postdateposition;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_date span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_date span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_date span
    {
        color:<?php echo $ocpc_postdatecolor;?>;
        font-size:<?php echo $ocpc_postdatefontsize."px";?>;
        font-weight:<?php echo $ocpc_postdatefweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_cats,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_cats,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_cats
    {
        text-align:<?php echo $ocpc_postcatsposition;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_cats span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_cats span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_cats span
    {
        color:<?php echo $ocpc_postcatscolor;?>;
        font-size:<?php echo $ocpc_postcatsfontsize."px";?>;
        font-weight:<?php echo $ocpc_postcatsfweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_cats span a,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_cats span a,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_cats span a
    {
        color:<?php echo $ocpc_postcatscolor;?>;
        font-size:<?php echo $ocpc_postcatsfontsize."px";?>;
        font-weight:<?php echo $ocpc_postcatsfweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_cats svg,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_cats svg,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_cats svg

    {
        width: <?php echo $ocpc_postcatsfontsize."px";?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_cats svg path,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_cats svg path,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_cats svg path
    {
        fill: <?php echo $ocpc_postcatscolor;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_author,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_author,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_author
    {
        text-align:<?php echo $ocpc_postauthorposition;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_author span,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_author span,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_author span
    {
        color:<?php echo $ocpc_postauthorcolor;?>;
        font-size:<?php echo $ocpc_postauthorfontsize."px";?>;
        font-weight:<?php echo $ocpc_postauthorfweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_glry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_crsol_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt6_msnry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt7_msnry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt8_msnry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt9_msnry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt10_msnry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt13_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt14_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt15_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt16_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt17_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt18_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt19_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt20_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt21_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt22_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt23_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt24_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt25_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt26_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt27_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt28_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt29_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt30_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt31_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt32_msnry_cont_dec,
	.ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_cont_dec
    {
        color:<?php echo $ocpc_postdescriptioncolor;?>;
        font-size:<?php echo $ocpc_postdescriptionfontsize."px";?>;
        text-align:<?php echo $ocpc_postdescriptionposition;?>;
        font-weight:<?php echo $ocpc_postdescriptionfweight;?>;
    }

    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_glry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_crsol_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt11_msnry_cont_dec,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt12_msnry_cont_dec {
    	display: inline-block;
        color:<?php echo $ocpc_postdescriptioncolor;?>;
        font-size:<?php echo $ocpc_postdescriptionfontsize."px";?>;
        font-weight:<?php echo $ocpc_postdescriptionfweight;?>;
    }
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_glry_main,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_crsol_main,
    .ocpc_slider_id_<?php echo $id; ?> .ocpc_tmplt33_msnry_main {
    	background: <?php echo $ocpc_trbgcolor; ?>;
    }
   	/*new templates after template no.5 css ends*/
</style>